# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwI4bwVsYJ2OjG181raiuF8yDwXlR_TP
"""

from sklearn.cluster import DBSCAN

import plotly.express as ex
import plotly.graph_objects as go

from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples = 1000, centers = 3)

ex.scatter(x = X[:, 0], y = X[:, 1])

dbscan = DBSCAN(eps = 0.9, min_samples = 3)

dbscan.fit(X)

labels = dbscan.labels_

ex.scatter(x = X[:, 0], y = X[:, 1], color = labels)

sum(labels == -1)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)

kmeans.fit(X)

labels_kmeans = kmeans.labels_

ex.scatter(x = X[:, 0], y = X[:, 1], color = labels_kmeans)

from sklearn.datasets import make_moons

X, y = make_moons(n_samples=10000, noise=0.1)

X

ex.scatter(x = X[:, 0], y = X[:, 1])

kmeans = KMeans(n_clusters=2)
dbscan = DBSCAN(eps = 0.7, min_samples = 5)

kmeans.fit(X)
dbscan.fit(X)

labels_km = kmeans.labels_
labels_ds = dbscan.labels_

ex.scatter(x = X[:, 0], y = X[:, 1], color=labels_km)

ex.scatter(x = X[:, 0], y = X[:, 1], color=labels_ds)