# -*- coding: utf-8 -*-
"""exemplo_árvore_decisão_base_crédito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7I9V5nZox6Ph76lix-rhrLn5Z81qR72
"""

import pandas as pd

dados = pd.read_csv('/content/Credit Score Classification Dataset.csv')

dados.head()

from sklearn.preprocessing import LabelEncoder

lb_encoder = LabelEncoder()

dados['Gender'] = lb_encoder.fit_transform(dados['Gender'])

dados.head(2)

dados['Education'] = lb_encoder.fit_transform(dados['Education'])
dados['Marital Status'] = lb_encoder.fit_transform(dados['Marital Status'])
dados['Home Ownership'] = lb_encoder.fit_transform(dados['Home Ownership'])
dados['Credit Score'] = lb_encoder.fit_transform(dados['Credit Score'])

dados.head(2)

"""## Separa os dados de entrada dos dados de saída"""



X = dados.iloc[:, 0:7].values

y = dados.iloc[:, -1].values

dados.shape

"""## Separa dados de treinamento de dados de teste"""

from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, shuffle = False)

X_teste.shape

"""## Construindo a árvore de decisão"""

from sklearn.tree import DecisionTreeClassifier

preditor = DecisionTreeClassifier()

preditor.fit(X_treino, y_treino)

preditor.score(X_teste, y_teste)

from sklearn import tree

tree.plot_tree(preditor)

respostas = preditor.predict(X_teste)

respostas

respostas == y_teste

