# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17F6lcLKE9f-ozP3LG4Qk04f2JOjAhFfU
"""

from sklearn.cluster import KMeans

from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=10000, centers=10)

X, y

import matplotlib.pyplot as plt

plt.scatter(x = X[:,0], y = X[:, 1])

import plotly.express as ex

ex.scatter(x = X[:, 0], y = X[:, 1])

k_means = KMeans(n_clusters = 10)

k_means.fit(X)

k_means.labels_

k_means.cluster_centers_

import plotly.graph_objects as go

centroides = k_means.cluster_centers_
labels = k_means.labels_

size = [6 for i in range(10)]

size

figura1 = ex.scatter(x = X[:, 0], y = X[:, 1], color = labels)
figura2 = ex.scatter(x = centroides[:,0], y = centroides[:, 1], size = size)
figura3 = go.Figure(data = figura1.data + figura2.data)
figura3.show()