# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7q1LkoBdLJCyrRLu9hIBoH1ILwXMVpn
"""

import pandas as pd

dados = pd.read_excel('/content/Exemplo Árvore de Decisão.xlsx')

dados

from sklearn.preprocessing import LabelEncoder

lb_encoder = LabelEncoder()

dados['Tempo'] = lb_encoder.fit_transform(dados['Tempo'])

dados['Vento'] = lb_encoder.fit_transform(dados['Vento'])

dados['Joga (sim/nao)'] = lb_encoder.fit_transform(dados['Joga (sim/nao)'])

dados

from sklearn import tree

arvore_decisao = tree.DecisionTreeClassifier(criterion='entropy')

dados

X = dados.iloc[:, 0:4]

X

y = dados.iloc[:, 4]

y

arvore_decisao.fit(X,y)

X.columns

tree.plot_tree(arvore_decisao, feature_names=X.columns, class_names=['Não', 'Sim'], filled=True)



teste = [2, 64,	65,	1]

teste

arvore_decisao.predict([teste])

arvore_decisao.score(X, y)

