# -*- coding: utf-8 -*-
"""Regressão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTTc5PwS4dX9tSQQCPc5h5l72KSabLE3
"""

import pandas as pd

dados_casas = pd.read_csv('/content/house_prices.csv')

dados_casas.head(5)

import matplotlib.pyplot as plt
import seaborn as sns

dados_casas.describe()

figura = plt.figure(figsize=(20, 20))
sns.heatmap(dados_casas.drop(columns='date').corr(), annot=True)

"""# Preparação dos dados"""

from sklearn.model_selection import train_test_split

X = dados_casas.iloc[:, 5].values
y = dados_casas.iloc[:, 2].values

X.shape

y.shape

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=0)

X_treino.shape

X_teste.shape

"""# Configuração do regressor linear"""

from sklearn.linear_model import LinearRegression

regressor_casas = LinearRegression()

regressor_casas.fit(X_treino.reshape(-1, 1), y_treino.reshape(-1, 1))

regressor_casas.coef_

regressor_casas.intercept_

X_teste[0]

y_teste[0]

1430 * 278.32860644 - 37893.59850107

regressor_casas.predict([[1430]])

regressor_casas.score(X_teste.reshape(-1, 1), y_teste.reshape(-1, 1))

"""# Regressão com Árvore de Decisão (regressão)"""

from sklearn.tree import DecisionTreeRegressor

casas_arvore = DecisionTreeRegressor(criterion='friedman_mse')

casas_arvore.fit(X_treino.reshape(-1, 1), y_treino.reshape(-1,1))

casas_arvore.score(X_teste.reshape(-1, 1), y_teste.reshape(-1, 1))

"""# Regressão com KNN"""

from sklearn.neighbors import KNeighborsRegressor

casas_knn = KNeighborsRegressor(n_neighbors=3)

casas_knn.fit(X_treino.reshape(-1, 1), y_treino.reshape(-1, 1))

casas_knn.score(X_teste.reshape(-1, 1), y_teste.reshape(-1, 1))

